name: Build Azul Java 21

on:
  push:
    branches: [ "master" ]  
  workflow_dispatch:


jobs:
  build-amd64:
    uses: ./.github/workflows/build-arch.yml
    with:
      arch: "amd64"
      java_version: ${{ vars.JAVA_21 }}
      download_url: ${{ vars.AZUL_21_URL_X64 }}
    secrets: inherit

  build-arm64:
    uses: ./.github/workflows/build-arch.yml
    with:
      arch: "arm64"
      java_version: ${{ vars.JAVA_21 }}
      download_url: ${{ vars.AZUL_21_URL_ARM64 }}
    secrets: inherit

  manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create bskjon/azuljava:${{ vars.JAVA_21 }} \
            --amend bskjon/azuljava@${{ needs.build-amd64.outputs.digest }} \
            --amend bskjon/azuljava@${{ needs.build-arm64.outputs.digest }}

          docker manifest push bskjon/azuljava:${{ vars.JAVA_21 }}
