name: Build Azul Java 21

on:
  workflow_dispatch:
    inputs:
      JAVA_VERSION:
        description: "Java version"
        required: true
        default: "21"

      AZUL_URL_X64:
        description: "Azul URL x64"
        required: true
        default: "https://cdn.azul.com/zulu/bin/zulu21.46.19-ca-jre21.0.9-linux_x64.tar.gz"

      AZUL_URL_ARM64:
        description: "Azul URL ARM64"
        required: true
        default: "https://cdn.azul.com/zulu/bin/zulu21.46.19-ca-jre21.0.9-linux_aarch64.tar.gz"


jobs:
  build-amd64:
    uses: ./.github/workflows/build-arch.yml
    with:
      arch: "amd64"
      java_version: ${{ inputs.JAVA_VERSION }}
      download_url: ${{ inputs.AZUL_URL_X64 }}
    secrets: inherit

  build-arm64:
    uses: ./.github/workflows/build-arch.yml
    with:
      arch: "arm64"
      java_version: ${{ inputs.JAVA_VERSION }}
      download_url: ${{ inputs.AZUL_URL_ARM64 }}
    secrets: inherit

  manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create bskjon/azuljava:${{ inputs.JAVA_VERSION }} \
            --amend bskjon/azuljava@${{ needs.build-amd64.outputs.digest }} \
            --amend bskjon/azuljava@${{ needs.build-arm64.outputs.digest }}

          docker manifest push bskjon/azuljava:${{ inputs.JAVA_VERSION }}
